### PR TITLE
fix: multiple instance, closes #72

### LINKED ISSUE #72: duplicate completions
sometimes it seems that it opens multiple instances.
config update?

### PR DESCRIPTION
**Pull request by antfu**

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -17,12 +17,13 @@ export async function activate(ctx: ExtensionContext) {
   const onUpdate = async () => {
     CORE = await init();
     DISPOSABLES.forEach(i => i.dispose());
-    DISPOSABLES = [...registerCompletions(ctx, CORE), ...registerCommands(ctx, CORE)];
+    DISPOSABLES.length = 0;
```
Comment (alexanderniebuhr) [inline src/extension.ts:20]: is this the same as
```
DISPOSABLES = [];
```

Comment (antfu) [reply src/extension.ts:20]: Nope, it creates a new instance and lost the reference and that's actually the reason of this bug

**Review by alexanderniebuhr — APPROVED** [review]
