### PR TITLE
fix: class sorting

### LINKED ISSUE #16: Sorting of color intensity is wrong
Hello,

I guess the lexicographic sorting might no en enough there, if we want 50 to be the first entry, for example 😅 

image

### PR DESCRIPTION
**Pull request by alexanderniebuhr**
fix class sorting with help of sortText based on index of the
colors same as tailwind does closes #16

### CODE REVIEW

File: src/lib/completions.ts [hunk 1]
```diff
@@ -56,18 +56,19 @@ export async function registerCompletions(ctx: ExtensionContext, core: Core): Pr
               return item;
             }): [];
 
-            const colorsCompletion = core.colorCompletions.map(({ label, detail, documentation}) => {
+            const colorsCompletion = core.colorCompletions.map(({ label, detail, documentation}, index) => {
               const color = new CompletionItem(label, CompletionItemKind.Color);
+              color.sortText = "-" + index.toString().replace(/\d+/g, ('00000000' + index).substr(-8));
```
Comment (antfu) [inline src/lib/completions.ts:61]: We can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart here

Comment (alexanderniebuhr) [reply src/lib/completions.ts:61]: will change 👍
